name: Update Media Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-media:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Debug environment variables
        env:
          TAUTULLI_URL: ${{ secrets.TAUTULLI_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "TAUTULLI_URL is set to: $TAUTULLI_URL"
          echo "API_KEY is set to: $API_KEY"

      - name: Verify working directory
        working-directory: scripts/datagen
        run: |
          pwd
          ls -la

      - name: Run update script
        env:
          TAUTULLI_URL: ${{ secrets.TAUTULLI_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        working-directory: scripts/datagen
        run: |
          python3 export.py || { echo "Script failed with exit code $?"; cat export.py; exit 1; }

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ../../data/gen/*.json ../../data/*.json ../../images/*/*
          git commit -m "Daily media update" || echo "No changes to commit"
          git push